# Setup
title:               Nasa Chart
tagline:             'SE-Asia'
description:         'Data Compendium of the NASA Chart project'
url:                 https://dvignoles.github.io/chart 
baseurl:             ''
#paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Daniel Vignoles
  url:               
  email:             dvignoles@gmail.com

# Gems
#plugins:
#  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
